# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2fcb1d2e13ad4bef088ce767ab2baa6bdb031a871d9f07f2c7f0c72328a427c4264624d34a3f80a1d34010b86cf1389132e426a5c585c6c32fc063f2d16b0e9b

test:
  secret_key_base: 52b2642c15836a4d9a25a454dc68f95a3a19ff50fc7a3cd1bf2b4a3d6f7faa44a453004e462967848ac1135cc9742d2ce1e4372059e7e638ccbe677df18bd962

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
